dist: "trusty"
sudo: required

language: ruby
addons:
  apt:
    packages:
      - "python3.5"
      - "python3-pip"

rvm:
  - 2.3.3
cache: bundler

before_script:
  - sudo -H python3.5 -m pip install --upgrade pip
  - sudo -H python3.5 -m pip install virtualenv
  - python3.5 -m virtualenv coala_check
  - source $TRAVIS_BUILD_DIR/coala_check/bin/activate
  - curl -fsSL -o coala.zip $coala_ZIP_URL/master
  - pip install coala.zip[alldeps] --pre -U
  - curl -fsSL -o coala-bears.zip $BEARS_ZIP_URL/master
  - pip install coala-bears.zip[alldeps] --pre -U

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
  - .ci/build.sh
  - coala --non-interactive

notifications:
  email: false
  webhooks: https://www.travisbuddy.com/
  on_success: never

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true  # Speeds installation of html-proofer
    - coala_ZIP_URL=https://codeload.github.com/coala/coala/zip
    - BEARS_ZIP_URL=https://codeload.github.com/coala/coala-bears/zip
